### ISSUE TITLE
DSM 7.0

### ISSUE THREAD

**Issue by grockk** [iBaa/PlexConnect#584]
The most recent release spk does not install on DSM 7.0.

![image](https://user-images.githubusercontent.com/62304715/92525722-56de2480-f1f2-11ea-8f16-bc4decd6b83d.png)

**Comment by moodyblue** [comment]
DSM7 is in preview mode. At the moment no user packages are supported (Plex included). I did not subscribe the preview, so I'm not able to create a PlexConnect spk for DSM7.

**Comment by moodyblue** [comment]
Maybe you are in luck. Plex support team will try to fix this.

**Comment by grockk** [comment]
Oh yes. Didn’t expect a quick fix. I just meant to open it as an issue to fix at some point. I’m running in virtual DSM.

**Comment by stevechen** [comment]
Plex is now working on DSM 7.0. PlexConnect can't be installed though. Hoping this will be fixed soon.

**Comment by grockk** [comment]
Has anyone tried installing PlexConnect on DSM 7? The spk package obviously doesn't work since it is for DSM 6. I wasn't sure if there is a manual install method?

**Comment by bloerwald** [comment]
> Has anyone tried installing PlexConnect on DSM 7? The spk package obviously doesn't work since it is for DSM 6. I wasn't sure if there is a manual install method?

I have been using the docker way of installing without issue:

`entrypoint.sh`
```
#!/bin/sh
echo "[PlexConnect]" > /PlexConnect/Settings.cfg
env | grep '^PLEXCONNECT_' | sed -E -e 's/^PLEXCONNECT_//' -e 's/(.*)=/\1 /' | awk '{printf "%s", tolower($1); $1=""; print " =" $0}' >> /PlexConnect/Settings.cfg
tail -F /PlexConnect/PlexConnect.log &
exec "${@}"
```
`Dockerfile`: 
```
FROM python:2-alpine
EXPOSE 53 80 443

ENV PLEXCONNECT_ENABLE_PLEXGDM=True \
    PLEXCONNECT_ENABLE_PLEXCONNECT_AUTODETECT=True \
    PLEXCONNECT_IP_PLEXCONNECT=0.0.0.0 \
    PLEXCONNECT_IP_PMS=xxx \
    PLEXCONNECT_PORT_PMS=32400 \
    PLEXCONNECT_IP_DNSMASTER=8.8.8.8 \
    PLEXCONNECT_PREVENT_ATV_UPDATE=True \
    PLEXCONNECT_HOSTTOINTERCEPT=trailers.apple.com \
    PLEXCONNECT_LOGLEVEL=Normal \
# py2-pillow installs there, but not in default search path, but pip install requires gcc etc
    PYTHONPATH=/usr/lib/python2.7/site-packages

RUN apk add --no-cache openssl git py2-pillow \
 && git clone https://github.com/iBaa/PlexConnect \
 && cd /PlexConnect/assets/certificates \
 && openssl req -new -nodes -newkey rsa:2048 -out trailers.pem -keyout trailers.key -x509 -days 365 -subj "/C=US/CN=trailers.apple.com" \
 && openssl x509 -in trailers.pem -outform der -out trailers.cer \
 && cat trailers.key >> trailers.pem

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

CMD python /PlexConnect/PlexConnect.py
```
`docker-compose.yml`
```
version: '2'
services:
  plexconnect:
    build: .
    container_name: plexconnect
    hostname: plexconnect
    networks:
      macprivate:
        ipv4_address: 192.168.178.201
      macpublic:
        ipv4_address: 192.168.179.201
    ports:
      - 443:443/tcp
      - 80:80/tcp
    volumes:
      - type: bind
        source: /volume1/docker/plexconnect/atvsettings.cfg
        target: /PlexConnect/ATVSettings.cfg
    restart: unless-stopped
    environment:
      PLEXCONNECT_LOGLEVEL: 'High'
      PLEXCONNECT_IP_PMS: 192.168.179.207
      PLEXCONNECT_ENABLE_PLEXCONNECT_AUTODETECT: 'False'
      PLEXCONNECT_ENABLE_PLEXGDM: 'False'
networks:
  macpublic:
    external: true
  macprivate:
    external: true
```
